question_data = [
    {
        "category": "Entertainment: Cartoon & Animations",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In the 'Shrek' film franchise, Donkey is played by Eddie Murphy.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Hippopotomonstrosesquippedaliophobia is the irrational fear of long words.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "DragonForce 'Through the Fire and Flames' is widely considered to be the hardest song in the Guitar Hero series.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Like with the Neanderthals, Homo sapiens sapiens also interbred with the Denisovans.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Japanese Anime & Manga",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In the 'Melancholy of Haruhi Suzumiya' series, the narrator goes by the nickname Kyon.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Television",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Like his character in 'Parks and Recreation', Aziz Ansari was born in South Carolina.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Television",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Klingons once had a period of Democracy in their history, they referred to it as the 'Dark Times'.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Cartoon & Animations",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Waylon Smithers from 'The Simpsons' was originally black when he first appeared in the series.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Board Games",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Rich Uncle Pennybags from the board game 'Monopoly' wears a monocle.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Not including false teeth; A human has two sets of teeth in their lifetime.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
]
